<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your country</name>
   <tag></tag>
   <elementGuidId>bb362834-184e-44c4-9f0f-1d02a89e0cc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='country']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#country</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;country&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5f3eaedd-ec80-4478-be4e-d24d374e8758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>c22d469d-f294-4cb2-991a-e27eb63211ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>d178c196-88e6-4aa4-8fe6-19c3a65c1ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>2bcc63b3-20ae-4473-95e5-5645e6aa91dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f541fad7-e1d9-47e8-95a1-524534fbe6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>a16a42d3-719a-457f-a6a9-64d60306425e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>d7a4dbda-5987-439b-b51b-4d2ada5fd052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>2e48a7ce-dd92-4fc7-a512-4b6ce4299917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your country *Albania Åland Islands Algeria American Samoa Andorra Angola Anguilla Antarctica Antigua and Barbuda Argentina Armenia Aruba Australia Austria Azerbaijan Bahamas (the) Bahrain Bangladesh Barbados Belarus Belgium Belize Benin Bermuda Bhutan Bolivia (Plurinational State of) Bonaire, Sint Eustatius and Saba Bosnia and Herzegovina Botswana Bouvet Island Brazil British Indian Ocean Territory (the) Brunei Darussalam Bulgaria Burkina Faso Burundi Cabo Verde Cambodia Cameroon Canada Cayman Islands (the) Central African Republic (the) Chad Chile China Christmas Island Cocos (Keeling) Islands (the) Colombia Comoros (the) Congo (the Democratic Republic of the) Congo (the) Cook Islands (the) Costa Rica Croatia Cuba Curaçao Cyprus Czechia Côte d'Ivoire Denmark Djibouti Dominica Dominican Republic (the) Ecuador Egypt El Salvador Equatorial Guinea Eritrea Estonia Eswatini Ethiopia Falkland Islands (the) [Malvinas] Faroe Islands (the) Fiji Finland France French Guiana French Polynesia French Southern Territories (the) Gabon Gambia (the) Georgia Germany Ghana Gibraltar Greece Greenland Grenada Guadeloupe Guam Guatemala Guernsey Guinea Guinea-Bissau Guyana Haiti Heard Island and McDonald Islands Holy See (the) Honduras Hong Kong Hungary Iceland India Indonesia Iran (Islamic Republic of) Iraq Ireland Isle of Man Israel Italy Jamaica Japan Jersey Jordan Kazakhstan Kenya Kiribati Korea (the Democratic People's Republic of) Korea (the Republic of) Kuwait Kyrgyzstan Lao People's Democratic Republic (the) Latvia Lebanon Lesotho Liberia Libya Liechtenstein Lithuania Luxembourg Macao Madagascar Malawi Malaysia Maldives Mali Malta Marshall Islands (the) Martinique Mauritania Mauritius Mayotte Mexico Micronesia (Federated States of) Moldova (the Republic of) Monaco Mongolia Montenegro Montserrat Morocco Mozambique Myanmar Namibia Nauru Nepal Netherlands (the) New Caledonia New Zealand Nicaragua Niger (the) Nigeria Niue Norfolk Island Northern Mariana Islands (the) Norway Oman Pakistan Palau Palestine, State of Panama Papua New Guinea Paraguay Peru Philippines (the) Pitcairn Poland Portugal Puerto Rico Qatar Republic of North Macedonia Romania Russian Federation (the) Rwanda Réunion Saint Barthélemy Saint Helena, Ascension and Tristan da Cunha Saint Kitts and Nevis Saint Lucia Saint Martin (French part) Saint Pierre and Miquelon Saint Vincent and the Grenadines Samoa San Marino Sao Tome and Principe Saudi Arabia Senegal Serbia Seychelles Sierra Leone Singapore Sint Maarten (Dutch part) Slovakia Slovenia Solomon Islands Somalia South Africa South Georgia and the South Sandwich Islands South Sudan Spain Sri Lanka Sudan (the) Suriname Svalbard and Jan Mayen Sweden Switzerland Syrian Arab Republic Taiwan (Province of China) Tajikistan Tanzania, United Republic of Thailand Timor-Leste Togo Tokelau Tonga Trinidad and Tobago Tunisia Turkey Turkmenistan Turks and Caicos Islands (the) Tuvalu Uganda Ukraine United Arab Emirates (the) United Kingdom of Great Britain and Northern Ireland (the) United States Minor Outlying Islands (the) United States of America (the) Uruguay Uzbekistan Vanuatu Venezuela (Bolivarian Republic of) Viet Nam Virgin Islands (British) Virgin Islands (U.S.) Wallis and Futuna Western Sahara Yemen Zambia Zimbabwe </value>
      <webElementGuid>e3c2cb34-61e9-4dde-a1b5-88ecff161471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;country&quot;)</value>
      <webElementGuid>e9d661e4-dfa1-4a8e-95b5-89ca53379f78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='country']</value>
      <webElementGuid>cf520d00-ec7f-45b5-867d-ec7688922023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::select[1]</value>
      <webElementGuid>68fd6f8a-759f-4d5a-91f3-c1eb0e947ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[1]</value>
      <webElementGuid>11111da1-a697-41f3-9d93-df78edbe0a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/preceding::select[1]</value>
      <webElementGuid>f6886982-8e12-44a8-b7dc-694c34dc40e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail address'])[1]/preceding::select[1]</value>
      <webElementGuid>998a35b0-64da-4422-81fa-d60f254f3cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>948ec412-3170-4551-8b3d-d0a7501bd977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'country' and (text() = concat(&quot;Select your country *Albania Åland Islands Algeria American Samoa Andorra Angola Anguilla Antarctica Antigua and Barbuda Argentina Armenia Aruba Australia Austria Azerbaijan Bahamas (the) Bahrain Bangladesh Barbados Belarus Belgium Belize Benin Bermuda Bhutan Bolivia (Plurinational State of) Bonaire, Sint Eustatius and Saba Bosnia and Herzegovina Botswana Bouvet Island Brazil British Indian Ocean Territory (the) Brunei Darussalam Bulgaria Burkina Faso Burundi Cabo Verde Cambodia Cameroon Canada Cayman Islands (the) Central African Republic (the) Chad Chile China Christmas Island Cocos (Keeling) Islands (the) Colombia Comoros (the) Congo (the Democratic Republic of the) Congo (the) Cook Islands (the) Costa Rica Croatia Cuba Curaçao Cyprus Czechia Côte d&quot; , &quot;'&quot; , &quot;Ivoire Denmark Djibouti Dominica Dominican Republic (the) Ecuador Egypt El Salvador Equatorial Guinea Eritrea Estonia Eswatini Ethiopia Falkland Islands (the) [Malvinas] Faroe Islands (the) Fiji Finland France French Guiana French Polynesia French Southern Territories (the) Gabon Gambia (the) Georgia Germany Ghana Gibraltar Greece Greenland Grenada Guadeloupe Guam Guatemala Guernsey Guinea Guinea-Bissau Guyana Haiti Heard Island and McDonald Islands Holy See (the) Honduras Hong Kong Hungary Iceland India Indonesia Iran (Islamic Republic of) Iraq Ireland Isle of Man Israel Italy Jamaica Japan Jersey Jordan Kazakhstan Kenya Kiribati Korea (the Democratic People&quot; , &quot;'&quot; , &quot;s Republic of) Korea (the Republic of) Kuwait Kyrgyzstan Lao People&quot; , &quot;'&quot; , &quot;s Democratic Republic (the) Latvia Lebanon Lesotho Liberia Libya Liechtenstein Lithuania Luxembourg Macao Madagascar Malawi Malaysia Maldives Mali Malta Marshall Islands (the) Martinique Mauritania Mauritius Mayotte Mexico Micronesia (Federated States of) Moldova (the Republic of) Monaco Mongolia Montenegro Montserrat Morocco Mozambique Myanmar Namibia Nauru Nepal Netherlands (the) New Caledonia New Zealand Nicaragua Niger (the) Nigeria Niue Norfolk Island Northern Mariana Islands (the) Norway Oman Pakistan Palau Palestine, State of Panama Papua New Guinea Paraguay Peru Philippines (the) Pitcairn Poland Portugal Puerto Rico Qatar Republic of North Macedonia Romania Russian Federation (the) Rwanda Réunion Saint Barthélemy Saint Helena, Ascension and Tristan da Cunha Saint Kitts and Nevis Saint Lucia Saint Martin (French part) Saint Pierre and Miquelon Saint Vincent and the Grenadines Samoa San Marino Sao Tome and Principe Saudi Arabia Senegal Serbia Seychelles Sierra Leone Singapore Sint Maarten (Dutch part) Slovakia Slovenia Solomon Islands Somalia South Africa South Georgia and the South Sandwich Islands South Sudan Spain Sri Lanka Sudan (the) Suriname Svalbard and Jan Mayen Sweden Switzerland Syrian Arab Republic Taiwan (Province of China) Tajikistan Tanzania, United Republic of Thailand Timor-Leste Togo Tokelau Tonga Trinidad and Tobago Tunisia Turkey Turkmenistan Turks and Caicos Islands (the) Tuvalu Uganda Ukraine United Arab Emirates (the) United Kingdom of Great Britain and Northern Ireland (the) United States Minor Outlying Islands (the) United States of America (the) Uruguay Uzbekistan Vanuatu Venezuela (Bolivarian Republic of) Viet Nam Virgin Islands (British) Virgin Islands (U.S.) Wallis and Futuna Western Sahara Yemen Zambia Zimbabwe &quot;) or . = concat(&quot;Select your country *Albania Åland Islands Algeria American Samoa Andorra Angola Anguilla Antarctica Antigua and Barbuda Argentina Armenia Aruba Australia Austria Azerbaijan Bahamas (the) Bahrain Bangladesh Barbados Belarus Belgium Belize Benin Bermuda Bhutan Bolivia (Plurinational State of) Bonaire, Sint Eustatius and Saba Bosnia and Herzegovina Botswana Bouvet Island Brazil British Indian Ocean Territory (the) Brunei Darussalam Bulgaria Burkina Faso Burundi Cabo Verde Cambodia Cameroon Canada Cayman Islands (the) Central African Republic (the) Chad Chile China Christmas Island Cocos (Keeling) Islands (the) Colombia Comoros (the) Congo (the Democratic Republic of the) Congo (the) Cook Islands (the) Costa Rica Croatia Cuba Curaçao Cyprus Czechia Côte d&quot; , &quot;'&quot; , &quot;Ivoire Denmark Djibouti Dominica Dominican Republic (the) Ecuador Egypt El Salvador Equatorial Guinea Eritrea Estonia Eswatini Ethiopia Falkland Islands (the) [Malvinas] Faroe Islands (the) Fiji Finland France French Guiana French Polynesia French Southern Territories (the) Gabon Gambia (the) Georgia Germany Ghana Gibraltar Greece Greenland Grenada Guadeloupe Guam Guatemala Guernsey Guinea Guinea-Bissau Guyana Haiti Heard Island and McDonald Islands Holy See (the) Honduras Hong Kong Hungary Iceland India Indonesia Iran (Islamic Republic of) Iraq Ireland Isle of Man Israel Italy Jamaica Japan Jersey Jordan Kazakhstan Kenya Kiribati Korea (the Democratic People&quot; , &quot;'&quot; , &quot;s Republic of) Korea (the Republic of) Kuwait Kyrgyzstan Lao People&quot; , &quot;'&quot; , &quot;s Democratic Republic (the) Latvia Lebanon Lesotho Liberia Libya Liechtenstein Lithuania Luxembourg Macao Madagascar Malawi Malaysia Maldives Mali Malta Marshall Islands (the) Martinique Mauritania Mauritius Mayotte Mexico Micronesia (Federated States of) Moldova (the Republic of) Monaco Mongolia Montenegro Montserrat Morocco Mozambique Myanmar Namibia Nauru Nepal Netherlands (the) New Caledonia New Zealand Nicaragua Niger (the) Nigeria Niue Norfolk Island Northern Mariana Islands (the) Norway Oman Pakistan Palau Palestine, State of Panama Papua New Guinea Paraguay Peru Philippines (the) Pitcairn Poland Portugal Puerto Rico Qatar Republic of North Macedonia Romania Russian Federation (the) Rwanda Réunion Saint Barthélemy Saint Helena, Ascension and Tristan da Cunha Saint Kitts and Nevis Saint Lucia Saint Martin (French part) Saint Pierre and Miquelon Saint Vincent and the Grenadines Samoa San Marino Sao Tome and Principe Saudi Arabia Senegal Serbia Seychelles Sierra Leone Singapore Sint Maarten (Dutch part) Slovakia Slovenia Solomon Islands Somalia South Africa South Georgia and the South Sandwich Islands South Sudan Spain Sri Lanka Sudan (the) Suriname Svalbard and Jan Mayen Sweden Switzerland Syrian Arab Republic Taiwan (Province of China) Tajikistan Tanzania, United Republic of Thailand Timor-Leste Togo Tokelau Tonga Trinidad and Tobago Tunisia Turkey Turkmenistan Turks and Caicos Islands (the) Tuvalu Uganda Ukraine United Arab Emirates (the) United Kingdom of Great Britain and Northern Ireland (the) United States Minor Outlying Islands (the) United States of America (the) Uruguay Uzbekistan Vanuatu Venezuela (Bolivarian Republic of) Viet Nam Virgin Islands (British) Virgin Islands (U.S.) Wallis and Futuna Western Sahara Yemen Zambia Zimbabwe &quot;))]</value>
      <webElementGuid>506e839b-7113-426d-8d1d-7dd07cf235d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
